### ISSUE TITLE
macOS `cargo-watch` fails to build (bin/run broken)

### ISSUE THREAD

**Issue by srid** [srid/rust-nix-template#15]
https://github.com/NixOS/nixpkgs/issues/146349

**Comment by srid** [comment]
Works in rosetta though (`--option system x86_64-darwin`).

**Comment by schickling** [comment]
> Works in rosetta though (`--option system x86_64-darwin`).

@srid can this be configured via a Nix flake as well?

**Comment by srid** [comment]
`nix develop --option system x86_64-darwin` should work; is that what you mean?

The proper way for this workaround, however, probably is to change this:

https://github.com/srid/rust-nix-template/blob/d2187b8dd874ec4d5c2ace6469b33a76b2592360/flake.nix#L26

to use the rosetta package, so that rosetta is used only for cargo-watch. cf. https://github.com/hercules-ci/flake-parts/issues/50#issuecomment-1212175176

**Comment by srid** [comment]
No longer an issue after #18
