### ISSUE TITLE
Formatters not working

### ISSUE THREAD

**Issue by 21CSM** [srid/rust-nix-template#36]
Getting an issue in both the terminal and vscode:

terminal:
```sh
just fmt
treefmt
sh: line 1: treefmt: command not found
error: Recipe `fmt` failed on line 6 with exit code 127
```

vscode:
```
Failed to run nixpkgs-fmt: spawn nixpkgs-fmt ENOENT
```

I have checked out [srid/nixci](https://github.com/srid/nixci) and that flake seems to be working well for me.

**Comment by srid** [comment]
Thanks for the report; I just forgot to include the treefmt devShell.

**Comment by 21CSM** [comment]
Thanks @srid! Confirming working now.
