### ISSUE TITLE
the sample usage command provided in readme now fails to initialise the project

### ISSUE THREAD

**Issue by conscious-puppet** [srid/rust-nix-template#40]
when using the following command to initialise the project:
```bash
DIR=sample-proj
mkdir $DIR && cd $DIR
nix --accept-flake-config run github:juspay/omnix -- init github:srid/rust-nix-template -o .
```

i get the following error:
```
Error: Output directory already exists: .
```

[![asciicast](https://asciinema.org/a/MUkfGZ4mVS3OOGLI8otF1Q3u6.svg)](https://asciinema.org/a/MUkfGZ4mVS3OOGLI8otF1Q3u6)

the following command to initialise the project works just fine:
```bash
nix --accept-flake-config run github:juspay/omnix -- init github:srid/rust-nix-template -o $PWD/sample-proj
```

[![asciicast](https://asciinema.org/a/7NMU6SJv3O20QFYakD5Pg8Gfg.svg)](https://asciinema.org/a/7NMU6SJv3O20QFYakD5Pg8Gfg)

**Comment by srid** [comment]
Yea omnix was changed to recently to require that dir to not exist.
