### ISSUE TITLE
Regarding `RUST_SRC_PATH`

### ISSUE THREAD

**Issue by NerdyPepper** [srid/rust-nix-template#5]
```rust
# FIXME: Is this correct? Should it use rust-overlay instead?
RUST_SRC_PATH = "${pkgs.rust.packages.stable.rustPlatform.rustLibSrc}";
```

This would work in most cases, but ideally, the `rust-src` component is on par with the active `rustc` toolchain (that is how `rustup` does it).

I source the `rust-src` component from `mozillapkgs` and export `RUST_SRC_PATH` like so (I think `oxalica/rust-overlay` also exposes the same `rust-src` component through `rust-bin.<channel>.latest.rust-src`):

```nix
RUST_SRC_PATH = "${rust-src}/lib/rustlib/src/rust/library";
```

`RUST_SRC_PATH` should contain the following:

```
alloc/        panic_unwind/       rustc-std-workspace-alloc/  stdarch/
backtrace/    proc_macro/         rustc-std-workspace-core/   term/
core/         profiler_builtins/  rustc-std-workspace-std/    test/
panic_abort/  rtstartup/          std/                        unwind/
```

There has been [some discussion](https://github.com/mozilla/nixpkgs-mozilla/issues/238) about providing `rust-src` from the nix store and `rust-analyzer` (`rust-analyzer` tries to write a `Cargo.lock` to the nix store and fails) but I have had no trouble with this.

I use this in my [rust + nix flake setup](https://git.peppe.rs/graphics/sdl-tests/tree/flake.nix#n26) (which has been modified heavily based on your template, thanks for that).

**Comment by srid** [comment]
Thanks for the info! Done in 0de7a6e480573d2d5397c136f56303ed588e4e98
