### ISSUE TITLE
Make sure to mention that Cargo.lock should be regenerated after renaming the project.

### ISSUE THREAD

**Issue by kjuulh** [srid/rust-nix-template#7]
This is normal for Rust development. But it does introduce some confusion when the project only mentions changing Cargo.toml and flake.nix. 

It will also give some vague error, as it will try to find the new package in the nix store. But it is obviously not there, as the project doesn't have that name in the store.

**Comment by tennox** [comment]
I didn't figure out how to do this without a workaround, as after changing the name the nix shell can't be opened:
```
++ crate2nix generate -f ./Cargo.toml -o Cargo-generated.nix -h /nix/store/mizxs1bm2jl30ylq6y2x419n1423ih4r-sonnen-scraper-crate2nix/crate-hashes.json
Error: while retrieving metadata about ./Cargo.toml: Error during execution of `cargo metadata`: error: the lock file /build/jyfdp6r1422lnbdklp6lkbz47l0cqh4k-source/Cargo.lock needs to be updated but --locked was passed to prevent this
```

I will submit a PR with Readme change shortly
