### ISSUE TITLE
buildRustCrate is deprecated

### ISSUE THREAD

**Issue by nouun** [srid/rust-nix-template#9]
When cloning the repo and trying to run `nix run` it errors with the following.
```
trace: warning: `buildRustCrate` is deprecated, use `buildRustCrateForPkgs` instead
trace: warning: `buildRustCrate` is deprecated, use `buildRustCrateForPkgs` instead
error: store path '/nix/store/v3svm8vpdb16pd1iblkh3dg4rhg8c0wq-rust-nix-template-crate2nix' is not allowed to have references
```

There's a section in the crate2nix FAQ about this.
https://github.com/kolloch/crate2nix#i-get-a-warning-about-buildrustcrate-being-deprecated-in-favor-of-buildrustcrateforpkgs

**Comment by srid** [comment]
Could use a PR fixing this.
